services:
  python-backend:
    container_name: python-backend
    build:
      context: ./services/python-backend
      dockerfile: Dockerfile_cpu
    environment:
      - TZ=Europe/Moscow  # Временная зона
      - APP_PORT=${APP_PORT} # Добавляем переменную для порта
    ports:
      - "8015:${APP_PORT}"
    volumes:
      - ./services/python-backend/app:/app/app:rw  # Для hot-reload кода
    env_file:
      - path: ./services/python-backend/.env
        required: True
    command: python3 app/main.py
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: "nvidia"
    #           count: all
    #           capabilities: [ "gpu" ]

  telegram-bot:
    container_name: telegram-bot
    build:
      context: ./services/telegram-bot
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - python-backend
    env_file:
      - path: ./services/telegram-bot/.env
        required: True
    restart: unless-stopped
    command: python3 bot/main.py